[project]
name = "clearml-lab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "clearml>=2.1.2",
    "clearml-session>=0.17.0",
    "ipykernel>=7.1.0",
    "pandas==2.0.3",
]
